### ISSUE TITLE
conn refused

### ISSUE THREAD

**Issue by dsisnero** [takkii/neoruby-debugger#87]
I am trying to use this for my ruby debugging experience but I always get connection refused

Couldn't connect to 127.0.0.1:38698 ECONNREFUSED

**Comment by takkii** [comment]
Hello, dsisnero

Have you read the neoruby-debugger documentation?

My environment and rbenv path, where I put rubygems/debug, etc.

Try trial and error to see what comes to mind

It's working in my environment

If that doesn't work, I think you can debug it with vscode.
